[workspace]
members = [
    "realtime-canvas-system",
    "realtime-canvas-wasm",
    "realtime-canvas-server",
    "realtime-canvas-pkg",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
